# Copyright © 2025 Cassidy Spring. 🖤 Sable Project.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: continuous-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test with swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] # ubuntu-latest
        swift: ["6.1", "6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2.3.0
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: build
        run: swift build
      - name: test
        run: swift test
