# Copyright © 2025 Cassidy Spring. 🖤 Sable Project.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: continuous-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test with swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, macos-14, ubuntu-latest]
        swift: ["6.1", "6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: beeauvin/swiftly-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: test
        run: swift test --parallel --enable-code-coverage

  coverage:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
      - name: test
        run: swift test --parallel --enable-code-coverage
      - name: report
        run: xcrun llvm-cov export -format=lcov .build/arm64-apple-macosx/debug/SablePackageTests.xctest/Contents/MacOS/SablePackageTests -instr-profile .build/arm64-apple-macosx/debug/codecov/default.profdata --ignore-filename-regex=".build|Tests" > coverage.lcov
      - name: coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
